require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const User = require('../models/User');
const Property = require('../models/Property');
const Visit = require('../models/Visit');
const SupportTicket = require('../models/SupportTicket');

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected to MongoDB');

  // Clear existing data
  await Promise.all([
    User.deleteMany({}),
    Property.deleteMany({}),
    Visit.deleteMany({}),
    SupportTicket.deleteMany({}),
  ]);
  console.log('Cleared existing data');

  // Create users
  const admin = await User.create({
    name: 'Nawazish',
    email: 'nawazish@gmail.com',
    password: 'admin@macbook',
    role: 'admin',
    phone: '+91-9000000001',
  });

  const tenant1 = await User.create({
    name: 'Rahul Sharma',
    email: 'tenant@demo.com',
    password: 'demo123',
    role: 'tenant',
    phone: '+91-9000000002',
  });

  const tenant2 = await User.create({
    name: 'Priya Patel',
    email: 'tenant2@demo.com',
    password: 'demo123',
    role: 'tenant',
    phone: '+91-9000000003',
  });

  console.log('Users created');

  // Create properties
  const propertyData = [
    {
      title: 'Modern 2BHK in Bandra West',
      description: 'Spacious 2BHK apartment with sea view, fully furnished with premium appliances. Located in the heart of Bandra, walking distance to shopping and dining.',
      location: 'Bandra West, Mumbai',
      city: 'Mumbai',
      price: 55000,
      type: '2BHK',
      images: ['https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800'],
      amenities: ['WiFi', 'Parking', 'Gym', 'Swimming Pool', 'Security', 'Power Backup'],
      rules: ['No Pets', 'No Smoking', 'No Loud Music after 10pm'],
      availableFrom: new Date('2026-03-01'),
      status: 'published',
      createdBy: admin._id,
    },
    {
      title: 'Cozy Studio in Koramangala',
      description: 'Well-maintained studio apartment perfect for working professionals. Close to major IT companies and cafes.',
      location: 'Koramangala, Bangalore',
      city: 'Bangalore',
      price: 22000,
      type: 'Studio',
      images: ['https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800'],
      amenities: ['WiFi', 'AC', 'Security', 'Laundry'],
      rules: ['No Pets', 'Working Professionals Only'],
      availableFrom: new Date('2026-03-10'),
      status: 'published',
      createdBy: admin._id,
    },
    {
      title: 'Luxury 3BHK Villa in Jubilee Hills',
      description: 'Premium 3BHK villa with private garden, modular kitchen, and premium interiors. Gated community with 24/7 security.',
      location: 'Jubilee Hills, Hyderabad',
      city: 'Hyderabad',
      price: 85000,
      type: '3BHK',
      images: ['https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800'],
      amenities: ['Private Garden', 'Parking x2', 'Gym', 'Club House', 'Kids Play Area', 'WiFi', 'Power Backup'],
      rules: ['Family Only', 'No Smoking', 'No Pets'],
      availableFrom: new Date('2026-04-01'),
      status: 'published',
      createdBy: admin._id,
    },
    {
      title: 'Affordable 1BHK in Andheri East',
      description: 'Budget-friendly 1BHK near metro station. Ideal for single professionals or couples.',
      location: 'Andheri East, Mumbai',
      city: 'Mumbai',
      price: 28000,
      type: '1BHK',
      images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
      amenities: ['WiFi', 'Security', 'Lift'],
      rules: ['No Smoking'],
      availableFrom: new Date('2026-03-15'),
      status: 'published',
      createdBy: admin._id,
    },
    {
      title: 'Premium 2BHK in HSR Layout',
      description: 'Semi-furnished 2BHK in premium society. Ample parking and green surroundings.',
      location: 'HSR Layout, Bangalore',
      city: 'Bangalore',
      price: 38000,
      type: '2BHK',
      images: ['https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800'],
      amenities: ['Parking', 'Security', 'Gym', 'WiFi', 'Power Backup'],
      rules: ['No Pets', 'No Smoking', 'Families Preferred'],
      availableFrom: new Date('2026-03-20'),
      status: 'published',
      createdBy: admin._id,
    },
    {
      title: 'Spacious Villa in Whitefield',
      description: 'Independent 4BHK villa with terrace garden. Perfect for large families.',
      location: 'Whitefield, Bangalore',
      city: 'Bangalore',
      price: 75000,
      type: 'Villa',
      images: ['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800'],
      amenities: ['Private Parking', 'Terrace Garden', 'Gym', 'Swimming Pool', 'Solar Panels'],
      rules: ['Family Only', 'No Parties'],
      availableFrom: new Date('2026-04-15'),
      status: 'published',
      createdBy: admin._id,
    },
    {
      title: '3BHK in Powai with Lake View',
      description: 'Beautiful lake-facing 3BHK in premium society. Well-connected to IT corridors.',
      location: 'Powai, Mumbai',
      city: 'Mumbai',
      price: 65000,
      type: '3BHK',
      images: ['https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800'],
      amenities: ['Lake View', 'Gym', 'Swimming Pool', 'Parking', 'Concierge', 'WiFi'],
      rules: ['No Smoking', 'No Loud Parties'],
      availableFrom: new Date('2026-03-25'),
      status: 'published',
      createdBy: admin._id,
    },
    {
      title: '1BHK Studio in Indiranagar',
      description: 'Modern studio apartment in the trendy Indiranagar locality. Cafes and pubs at doorstep.',
      location: 'Indiranagar, Bangalore',
      city: 'Bangalore',
      price: 25000,
      type: '1BHK',
      images: ['https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800'],
      amenities: ['WiFi', 'AC', 'Security', 'Lift'],
      rules: ['Working Professionals', 'No Smoking Inside'],
      availableFrom: new Date('2026-03-01'),
      status: 'published',
      createdBy: admin._id,
    },
    {
      title: 'Newly Built 2BHK in Gachibowli',
      description: 'Brand new 2BHK in IT hub. Modular kitchen, vitrified flooring, and great ventilation.',
      location: 'Gachibowli, Hyderabad',
      city: 'Hyderabad',
      price: 32000,
      type: '2BHK',
      images: ['https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?w=800'],
      amenities: ['Parking', 'Gym', 'Children Play Area', 'WiFi', 'CCTV'],
      rules: ['No Smoking', 'No Pets'],
      availableFrom: new Date('2026-03-10'),
      status: 'review',
      createdBy: admin._id,
    },
    {
      title: 'Heritage Apartment in South Delhi',
      description: 'Classic apartment in posh South Delhi colony. Close to markets and schools.',
      location: 'Greater Kailash, Delhi',
      city: 'Delhi',
      price: 48000,
      type: '2BHK',
      images: ['https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800'],
      amenities: ['Parking', 'Security', 'Garden', 'Power Backup'],
      rules: ['Family Only', 'No Smoking', 'No Pets'],
      availableFrom: new Date('2026-04-01'),
      status: 'published',
      createdBy: admin._id,
    },

    // ── PUNE (5) ──
    {
      title: 'Cozy 1BHK in Kothrud',
      description: 'Well-maintained 1BHK in a quiet residential colony. Close to Pune University and Deccan Gymkhana.',
      location: 'Kothrud, Pune', city: 'Pune', price: 18000, type: '1BHK',
      images: ['https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800'],
      amenities: ['WiFi', 'Security', 'Lift', 'Water Supply'],
      rules: ['No Smoking', 'Working Professionals Only'],
      availableFrom: new Date('2026-03-10'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Spacious 2BHK in Baner',
      description: 'Modern semi-furnished 2BHK in Baner IT corridor. Close to Hinjewadi tech park and multiple malls.',
      location: 'Baner, Pune', city: 'Pune', price: 30000, type: '2BHK',
      images: ['https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800'],
      amenities: ['WiFi', 'Parking', 'Gym', 'Power Backup', 'CCTV'],
      rules: ['No Pets', 'No Smoking'],
      availableFrom: new Date('2026-03-15'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Premium 3BHK in Kalyani Nagar',
      description: 'Luxuriously furnished 3BHK in upscale Kalyani Nagar. Walking distance to restaurants, offices and malls.',
      location: 'Kalyani Nagar, Pune', city: 'Pune', price: 52000, type: '3BHK',
      images: ['https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800'],
      amenities: ['Gym', 'Swimming Pool', 'Parking x2', 'Security', 'Club House', 'WiFi'],
      rules: ['Family Only', 'No Loud Music'],
      availableFrom: new Date('2026-04-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Studio Apartment in Wakad',
      description: 'Compact and affordable studio near Hinjewadi Phase 1. Ideal for solo IT professionals. Fully furnished with AC.',
      location: 'Wakad, Pune', city: 'Pune', price: 14000, type: 'Studio',
      images: ['https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800'],
      amenities: ['WiFi', 'AC', 'Security', 'Laundry'],
      rules: ['No Smoking', 'Working Professionals Only'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Independent Villa in Aundh',
      description: 'Beautiful independent 4BHK villa with private garden in the posh Aundh neighbourhood.',
      location: 'Aundh, Pune', city: 'Pune', price: 70000, type: 'Villa',
      images: ['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800'],
      amenities: ['Private Garden', 'Parking x2', 'Solar Panels', 'CCTV', 'Terrace'],
      rules: ['Family Only', 'No Parties', 'No Pets'],
      availableFrom: new Date('2026-04-15'), status: 'published', createdBy: admin._id,
    },

    // ── CHENNAI (5) ──
    {
      title: 'Modern 2BHK in Velachery',
      description: 'Fully furnished 2BHK near Phoenix Mall and Velachery Metro. Close to IT parks in Sholinganallur.',
      location: 'Velachery, Chennai', city: 'Chennai', price: 24000, type: '2BHK',
      images: ['https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800'],
      amenities: ['WiFi', 'AC', 'Parking', 'Security', 'Lift'],
      rules: ['No Smoking', 'No Pets'],
      availableFrom: new Date('2026-03-10'), status: 'published', createdBy: admin._id,
    },
    {
      title: '1BHK in Anna Nagar',
      description: 'Well-ventilated 1BHK in sought-after Anna Nagar. Walking distance to parks, markets and metro.',
      location: 'Anna Nagar, Chennai', city: 'Chennai', price: 17000, type: '1BHK',
      images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
      amenities: ['Security', 'Water Supply', 'Power Backup', 'Lift'],
      rules: ['No Smoking', 'Families Preferred'],
      availableFrom: new Date('2026-03-20'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Luxury 3BHK in Adyar',
      description: 'Premium 3BHK with sea breeze in Adyar. Close to Besant Nagar beach and IIT Madras.',
      location: 'Adyar, Chennai', city: 'Chennai', price: 48000, type: '3BHK',
      images: ['https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800'],
      amenities: ['Swimming Pool', 'Gym', 'Parking', 'Club House', 'WiFi', 'Power Backup'],
      rules: ['Family Only', 'No Smoking'],
      availableFrom: new Date('2026-04-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Studio in OMR Tech Corridor',
      description: 'Affordable studio in the heart of OMR. Walking distance to TCS, Infosys and Cognizant campuses.',
      location: 'OMR, Chennai', city: 'Chennai', price: 12000, type: 'Studio',
      images: ['https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?w=800'],
      amenities: ['WiFi', 'AC', 'Security', 'Parking'],
      rules: ['IT Professionals Only', 'No Smoking'],
      availableFrom: new Date('2026-03-05'), status: 'published', createdBy: admin._id,
    },
    {
      title: '2BHK Villa on ECR',
      description: 'Charming villa-style 2BHK on East Coast Road with partial sea view. Perfect for beach lifestyle.',
      location: 'East Coast Road, Chennai', city: 'Chennai', price: 35000, type: '2BHK',
      images: ['https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800'],
      amenities: ['Sea View', 'Private Parking', 'Garden', 'Security'],
      rules: ['No Smoking', 'Families Preferred'],
      availableFrom: new Date('2026-03-25'), status: 'published', createdBy: admin._id,
    },

    // ── KOLKATA (5) ──
    {
      title: '2BHK in Salt Lake Sector V',
      description: "Spacious 2BHK in Kolkata's IT hub. Walking distance to TCS, Wipro and Cognizant. Well connected by metro.",
      location: 'Salt Lake Sector V, Kolkata', city: 'Kolkata', price: 20000, type: '2BHK',
      images: ['https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800'],
      amenities: ['WiFi', 'AC', 'Security', 'Parking', 'Power Backup'],
      rules: ['No Smoking', 'No Pets'],
      availableFrom: new Date('2026-03-10'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Classic 3BHK in Ballygunge',
      description: 'Traditional yet renovated 3BHK in heritage Ballygunge. High ceilings, wooden floors, and vintage charm.',
      location: 'Ballygunge, Kolkata', city: 'Kolkata', price: 38000, type: '3BHK',
      images: ['https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800'],
      amenities: ['Parking', 'Security', 'Garden', 'Power Backup'],
      rules: ['Family Only', 'No Smoking'],
      availableFrom: new Date('2026-04-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Affordable 1BHK in Dum Dum',
      description: 'Budget 1BHK near Dum Dum Metro and airport. Great for daily commuters and working professionals.',
      location: 'Dum Dum, Kolkata', city: 'Kolkata', price: 10000, type: '1BHK',
      images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
      amenities: ['Security', 'Water Supply', 'Lift'],
      rules: ['No Smoking'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Studio in New Town Action Area',
      description: "Modern studio in Kolkata's planned smart city near eco park and business hubs.",
      location: 'New Town, Kolkata', city: 'Kolkata', price: 13000, type: 'Studio',
      images: ['https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800'],
      amenities: ['WiFi', 'AC', 'Security', 'Gym'],
      rules: ['Working Professionals Only', 'No Smoking'],
      availableFrom: new Date('2026-03-15'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Premium 2BHK on Park Street',
      description: "Elegant 2BHK in iconic Park Street. Surrounded by top restaurants, cafes and the city's best nightlife.",
      location: 'Park Street, Kolkata', city: 'Kolkata', price: 32000, type: '2BHK',
      images: ['https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800'],
      amenities: ['WiFi', 'AC', 'Security', 'Lift', 'Power Backup'],
      rules: ['No Smoking', 'No Loud Music after 11pm'],
      availableFrom: new Date('2026-03-20'), status: 'published', createdBy: admin._id,
    },

    // ── AHMEDABAD (5) ──
    {
      title: 'Modern 2BHK in Satellite',
      description: "Contemporary 2BHK in Ahmedabad's upscale Satellite area. Close to premium malls and SG Highway.",
      location: 'Satellite, Ahmedabad', city: 'Ahmedabad', price: 22000, type: '2BHK',
      images: ['https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800'],
      amenities: ['WiFi', 'AC', 'Parking', 'Gym', 'Security', 'Power Backup'],
      rules: ['No Smoking', 'No Non-Veg Cooking'],
      availableFrom: new Date('2026-03-10'), status: 'published', createdBy: admin._id,
    },
    {
      title: '3BHK Bungalow in Bopal',
      description: 'Spacious independent bungalow in fast-developing Bopal. Easy access to SG Highway.',
      location: 'Bopal, Ahmedabad', city: 'Ahmedabad', price: 45000, type: 'Villa',
      images: ['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800'],
      amenities: ['Private Parking x2', 'Garden', 'Security', 'Power Backup', 'Solar Panels'],
      rules: ['Family Only', 'No Smoking'],
      availableFrom: new Date('2026-04-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: '1BHK in Navrangpura',
      description: 'Centrally located 1BHK near CEPT University and Law Garden. Walkable to eateries and shops.',
      location: 'Navrangpura, Ahmedabad', city: 'Ahmedabad', price: 14000, type: '1BHK',
      images: ['https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800'],
      amenities: ['WiFi', 'Security', 'Lift', 'Water Supply'],
      rules: ['No Smoking', 'Vegetarian Preferred'],
      availableFrom: new Date('2026-03-05'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Studio in Prahlad Nagar',
      description: "Stylish studio in Ahmedabad's corporate hub. Walking distance to GIFT City feeder roads and major offices.",
      location: 'Prahlad Nagar, Ahmedabad', city: 'Ahmedabad', price: 16000, type: 'Studio',
      images: ['https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?w=800'],
      amenities: ['WiFi', 'AC', 'Security', 'Parking'],
      rules: ['Working Professionals Only', 'No Smoking'],
      availableFrom: new Date('2026-03-15'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Luxury 3BHK in Bodakdev',
      description: "Premium 3BHK in one of Ahmedabad's most prestigious localities. Top-of-the-line interiors.",
      location: 'Bodakdev, Ahmedabad', city: 'Ahmedabad', price: 55000, type: '3BHK',
      images: ['https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800'],
      amenities: ['Swimming Pool', 'Gym', 'Parking x2', 'Club House', 'WiFi', 'CCTV'],
      rules: ['Family Only', 'No Smoking'],
      availableFrom: new Date('2026-04-10'), status: 'published', createdBy: admin._id,
    },

    // ── MORE MUMBAI (4) ──
    {
      title: '1BHK in Thane West',
      description: 'Affordable 1BHK near Viviana Mall. Fast connectivity to Mumbai via rail.',
      location: 'Thane West, Mumbai', city: 'Mumbai', price: 21000, type: '1BHK',
      images: ['https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800'],
      amenities: ['Security', 'Parking', 'Gym', 'Power Backup'],
      rules: ['No Smoking', 'No Pets'],
      availableFrom: new Date('2026-03-12'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Studio in Lower Parel',
      description: "Compact studio in Mumbai's corporate heartland. Walking distance to Phoenix Palladium and major offices.",
      location: 'Lower Parel, Mumbai', city: 'Mumbai', price: 35000, type: 'Studio',
      images: ['https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800'],
      amenities: ['WiFi', 'AC', 'Gym', 'Security', 'Concierge'],
      rules: ['No Smoking', 'Working Professionals Only'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: '3BHK Sea-Facing Flat in Worli',
      description: 'Stunning sea-facing 3BHK with panoramic Arabian Sea views. Premium finishes and private balcony.',
      location: 'Worli, Mumbai', city: 'Mumbai', price: 120000, type: '3BHK',
      images: ['https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800'],
      amenities: ['Sea View', 'Swimming Pool', 'Gym', 'Concierge', 'Parking x2', 'WiFi'],
      rules: ['No Smoking', 'No Loud Parties', 'Family Only'],
      availableFrom: new Date('2026-04-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: '2BHK in Kharghar, Navi Mumbai',
      description: 'Newly constructed 2BHK in the planned Kharghar township. Close to Central Park and Kharghar metro.',
      location: 'Kharghar, Navi Mumbai', city: 'Mumbai', price: 26000, type: '2BHK',
      images: ['https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800'],
      amenities: ['Gym', 'Swimming Pool', 'Parking', 'Security', 'WiFi'],
      rules: ['No Pets', 'No Smoking'],
      availableFrom: new Date('2026-03-20'), status: 'published', createdBy: admin._id,
    },

    // ── MORE BANGALORE (4) ──
    {
      title: '2BHK on Sarjapur Road',
      description: 'Modern 2BHK near major tech parks. Close to Wipro, Accenture and Ecospace on Outer Ring Road.',
      location: 'Sarjapur Road, Bangalore', city: 'Bangalore', price: 35000, type: '2BHK',
      images: ['https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800'],
      amenities: ['WiFi', 'Parking', 'Gym', 'Security', 'Power Backup'],
      rules: ['No Smoking', 'No Pets'],
      availableFrom: new Date('2026-03-15'), status: 'published', createdBy: admin._id,
    },
    {
      title: '1BHK in Electronic City Phase 2',
      description: 'Budget-friendly 1BHK steps from Infosys and HCL campuses. BMTC Volvo bus at doorstep.',
      location: 'Electronic City, Bangalore', city: 'Bangalore', price: 16000, type: '1BHK',
      images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
      amenities: ['WiFi', 'Security', 'Water Supply', 'Parking'],
      rules: ['IT Professionals Only', 'No Smoking'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Penthouse Studio on MG Road',
      description: 'Swanky penthouse studio with city skyline view on MG Road. Steps from metro and Brigade Road.',
      location: 'MG Road, Bangalore', city: 'Bangalore', price: 40000, type: 'Studio',
      images: ['https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800'],
      amenities: ['Rooftop Access', 'AC', 'WiFi', 'Security', 'Concierge'],
      rules: ['No Smoking', 'Working Professionals Only'],
      availableFrom: new Date('2026-03-10'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Luxury Villa in Devanahalli',
      description: 'Sprawling 5BHK villa near Kempegowda International Airport. Ideal for expats and senior executives.',
      location: 'Devanahalli, Bangalore', city: 'Bangalore', price: 95000, type: 'Villa',
      images: ['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800'],
      amenities: ['Private Pool', 'Home Theatre', 'Parking x3', 'Garden', 'Security', 'Solar'],
      rules: ['Family Only', 'No Events'],
      availableFrom: new Date('2026-04-20'), status: 'published', createdBy: admin._id,
    },

    // ── MORE DELHI (4) ──
    {
      title: '2BHK in Dwarka Sector 12',
      description: 'Spacious 2BHK in planned Dwarka. Direct metro connectivity to Connaught Place and IGI Airport.',
      location: 'Dwarka Sector 12, Delhi', city: 'Delhi', price: 28000, type: '2BHK',
      images: ['https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?w=800'],
      amenities: ['Parking', 'Security', 'Lift', 'Power Backup', 'WiFi'],
      rules: ['No Smoking', 'Family Preferred'],
      availableFrom: new Date('2026-03-15'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Studio near Connaught Place',
      description: 'Premium studio near CP metro. Walk to India Gate, Janpath Market and top restaurants.',
      location: 'Connaught Place, Delhi', city: 'Delhi', price: 42000, type: 'Studio',
      images: ['https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800'],
      amenities: ['WiFi', 'AC', 'Security', 'Concierge', 'Gym'],
      rules: ['Working Professionals Only', 'No Smoking'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Luxury 3BHK in Vasant Vihar',
      description: "Elegant 3BHK in Delhi's most prestigious diplomatic enclave. Minutes from DLF Promenade.",
      location: 'Vasant Vihar, Delhi', city: 'Delhi', price: 85000, type: '3BHK',
      images: ['https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800'],
      amenities: ['Club House', 'Swimming Pool', 'Gym', 'Parking x2', 'Security', 'WiFi'],
      rules: ['Family Only', 'No Smoking', 'No Pets'],
      availableFrom: new Date('2026-04-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: '1BHK in Lajpat Nagar',
      description: 'Affordable 1BHK in lively Lajpat Nagar. Close to metro, Central Market and hospitals.',
      location: 'Lajpat Nagar, Delhi', city: 'Delhi', price: 20000, type: '1BHK',
      images: ['https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800'],
      amenities: ['Security', 'Lift', 'Power Backup', 'Water Supply'],
      rules: ['No Smoking', 'Families Preferred'],
      availableFrom: new Date('2026-03-20'), status: 'draft', createdBy: admin._id,
    },

    // ── MORE HYDERABAD (2) ──
    {
      title: '1BHK in HITEC City',
      description: 'Well-located 1BHK steps from HITEC City metro. Ideal for tech professionals in Cyberabad.',
      location: 'HITEC City, Hyderabad', city: 'Hyderabad', price: 20000, type: '1BHK',
      images: ['https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800'],
      amenities: ['WiFi', 'Security', 'Parking', 'Gym'],
      rules: ['No Smoking', 'IT Professionals Preferred'],
      availableFrom: new Date('2026-03-10'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Premium Villa in Kokapet',
      description: 'Premium independent villa in the emerging Kokapet Golden Mile corridor. Close to Financial District.',
      location: 'Kokapet, Hyderabad', city: 'Hyderabad', price: 90000, type: 'Villa',
      images: ['https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800'],
      amenities: ['Private Pool', 'Home Theatre', 'Garden', 'Parking x3', 'Solar Panels', 'Security'],
      rules: ['Family Only', 'No Events', 'No Smoking'],
      availableFrom: new Date('2026-05-01'), status: 'review', createdBy: admin._id,
    },

    // ── EXTRA (6 more to reach 50) ──
    {
      title: '2BHK in Gurgaon Sector 56',
      description: 'Well-furnished 2BHK in Gurgaon near Golf Course Extension Road. Close to corporate hubs and malls.',
      location: 'Sector 56, Gurgaon', city: 'Delhi', price: 38000, type: '2BHK',
      images: ['https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800'],
      amenities: ['WiFi', 'Gym', 'Parking', 'Swimming Pool', 'Security', 'Power Backup'],
      rules: ['No Smoking', 'No Pets'],
      availableFrom: new Date('2026-03-15'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Villa in Noida Sector 50',
      description: 'Stunning 4BHK villa in premium Noida society. Easy metro access to Delhi and Connaught Place.',
      location: 'Sector 50, Noida', city: 'Delhi', price: 65000, type: 'Villa',
      images: ['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800'],
      amenities: ['Club House', 'Swimming Pool', 'Gym', 'Parking x2', 'CCTV', 'Garden'],
      rules: ['Family Only', 'No Smoking'],
      availableFrom: new Date('2026-04-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: '1BHK in Hinjewadi Phase 3',
      description: 'Smart 1BHK inside Hinjewadi IT hub. Zero commute for tech professionals. Modern interiors.',
      location: 'Hinjewadi Phase 3, Pune', city: 'Pune', price: 20000, type: '1BHK',
      images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
      amenities: ['WiFi', 'AC', 'Security', 'Gym', 'Laundry'],
      rules: ['IT Professionals Only', 'No Smoking'],
      availableFrom: new Date('2026-03-10'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Sea View Studio in Navi Mumbai',
      description: 'Modern studio apartment in Palm Beach Road with partial creek view. Close to Vashi IT park.',
      location: 'Palm Beach Road, Navi Mumbai', city: 'Mumbai', price: 28000, type: 'Studio',
      images: ['https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800'],
      amenities: ['AC', 'WiFi', 'Gym', 'Security', 'Parking', 'Creek View'],
      rules: ['No Smoking', 'Working Professionals Preferred'],
      availableFrom: new Date('2026-03-20'), status: 'published', createdBy: admin._id,
    },
    {
      title: '3BHK in Hebbal, Bangalore',
      description: 'Premium 3BHK near Manyata Tech Park and Hebbal flyover. Excellent connectivity to airport.',
      location: 'Hebbal, Bangalore', city: 'Bangalore', price: 48000, type: '3BHK',
      images: ['https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800'],
      amenities: ['Swimming Pool', 'Gym', 'Parking', 'Club House', 'WiFi', 'CCTV'],
      rules: ['Family Preferred', 'No Smoking'],
      availableFrom: new Date('2026-04-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Budget 1BHK in Perambur, Chennai',
      description: 'Clean and affordable 1BHK near Perambur railway station. Good connectivity across Chennai.',
      location: 'Perambur, Chennai', city: 'Chennai', price: 10000, type: '1BHK',
      images: ['https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?w=800'],
      amenities: ['Water Supply', 'Security', 'Lift'],
      rules: ['No Smoking', 'Families Preferred'],
      availableFrom: new Date('2026-03-05'), status: 'published', createdBy: admin._id,
    },

    // ── HOSTELS (1 per city × 8 cities) ──
    {
      title: 'The Bunk House — Bandra Hostel',
      description: 'Trendy co-living hostel in Bandra with mixed dorms and private pods. Rooftop hangout, fast WiFi, free breakfast. Perfect for backpackers and solo travellers.',
      location: 'Bandra West, Mumbai', city: 'Mumbai', price: 1100, type: 'Hostel',
      images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800'],
      amenities: ['Free Breakfast', 'WiFi', 'Rooftop', 'Lockers', 'Common Kitchen', 'AC'],
      rules: ['No Smoking Inside', 'Quiet Hours 11pm–7am', 'ID Required'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Zostel Koramangala Bangalore',
      description: 'Popular backpacker hostel in Koramangala with vibrant social spaces, movie nights and city tours. Dorm beds and private rooms available.',
      location: 'Koramangala, Bangalore', city: 'Bangalore', price: 899, type: 'Hostel',
      images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800'],
      amenities: ['WiFi', 'Lockers', 'Common Room', 'Free Events', 'Laundry', 'AC'],
      rules: ['No Smoking', 'No Outside Guests after 11pm', 'ID Required'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Urban Nest Hostel — Jubilee Hills',
      description: 'Clean and safe hostel in central Hyderabad. Separate male/female dorms, 24hr security and a great common area to meet fellow travellers.',
      location: 'Jubilee Hills, Hyderabad', city: 'Hyderabad', price: 750, type: 'Hostel',
      images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800'],
      amenities: ['WiFi', 'Lockers', 'Hot Water', 'Security', 'Common Kitchen', 'AC'],
      rules: ['No Alcohol', 'Quiet Hours 10pm–7am', 'ID Required'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Paharganj Budget Hostel',
      description: 'Classic budget hostel in the heart of Paharganj backpacker district, Delhi. Steps from New Delhi Railway Station and metro.',
      location: 'Paharganj, Delhi', city: 'Delhi', price: 599, type: 'Hostel',
      images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800'],
      amenities: ['WiFi', 'Lockers', 'Common Area', '24hr Reception', 'Luggage Storage'],
      rules: ['No Smoking Inside', 'ID Required', 'Check-out by 11am'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Wanderers Den — Koregaon Park Hostel',
      description: 'Lively hostel in Pune\'s party hub Koregaon Park. Rooftop bar access, free walking tours and mix of private and dorm rooms.',
      location: 'Koregaon Park, Pune', city: 'Pune', price: 950, type: 'Hostel',
      images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800'],
      amenities: ['WiFi', 'Rooftop', 'Free Walking Tour', 'AC', 'Lockers', 'Common Kitchen'],
      rules: ['No Smoking Inside', 'ID Required', 'Quiet Hours after Midnight'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Chennai Backpackers Inn — T Nagar',
      description: 'Affordable dorms and private rooms in T Nagar, the shopping hub of Chennai. Friendly staff, clean facilities, close to bus and metro.',
      location: 'T Nagar, Chennai', city: 'Chennai', price: 699, type: 'Hostel',
      images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800'],
      amenities: ['WiFi', 'Lockers', 'AC', 'Common Kitchen', 'Luggage Storage', 'Security'],
      rules: ['No Smoking', 'ID Required', 'Check-out by 11am'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'The Calcutta Commune — Hostel',
      description: 'Heritage building hostel near Park Street, Kolkata. Art-filled walls, book exchange, rooftop terrace and weekly cultural events.',
      location: 'Park Street, Kolkata', city: 'Kolkata', price: 800, type: 'Hostel',
      images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800'],
      amenities: ['WiFi', 'Rooftop Terrace', 'Book Exchange', 'AC', 'Lockers', 'Common Room'],
      rules: ['No Smoking Inside', 'ID Required', 'Quiet Hours 11pm–7am'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Ahmedabad Heritage Hostel',
      description: 'Stay in a restored pol-house in Ahmedabad\'s UNESCO World Heritage old city. Dorm beds and private rooms with traditional Gujarati architecture.',
      location: 'Old City, Ahmedabad', city: 'Ahmedabad', price: 650, type: 'Hostel',
      images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800'],
      amenities: ['WiFi', 'Heritage Architecture', 'Guided Tours', 'Common Kitchen', 'Lockers'],
      rules: ['No Smoking', 'No Alcohol on Premises', 'ID Required'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },

    // ── AIRBNBS (2 per city × 8 cities = 16) ──
    // Mumbai Airbnbs
    {
      title: 'Chic Studio Airbnb in Colaba',
      description: 'Stylish self-contained studio near Gateway of India. Fully equipped kitchen, fast WiFi, Netflix and a cosy workspace. Ideal for solo trips and short stays.',
      location: 'Colaba, Mumbai', city: 'Mumbai', price: 3500, type: 'Airbnb',
      images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
      amenities: ['WiFi', 'Netflix', 'AC', 'Kitchen', 'Workspace', 'Self Check-in'],
      rules: ['No Smoking', 'No Parties', 'Checkout 11am'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Beachfront 2BHK Airbnb — Juhu',
      description: 'Wake up to sea breeze in this beautiful 2BHK just 2 minutes from Juhu Beach. Full home amenities, perfect for families and couples.',
      location: 'Juhu, Mumbai', city: 'Mumbai', price: 7500, type: 'Airbnb',
      images: ['https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800'],
      amenities: ['Beach Access', 'WiFi', 'AC', 'Full Kitchen', 'Parking', 'Washer'],
      rules: ['No Smoking', 'No Loud Music', 'Max 4 Guests'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    // Bangalore Airbnbs
    {
      title: 'Artist Loft Airbnb — Indiranagar',
      description: 'Quirky artist-designed loft apartment in Indiranagar. Walking distance to 100 Feet Road cafes and nightlife. Perfect weekend getaway.',
      location: 'Indiranagar, Bangalore', city: 'Bangalore', price: 4200, type: 'Airbnb',
      images: ['https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800'],
      amenities: ['WiFi', 'AC', 'Netflix', 'Workspace', 'Self Check-in', 'Kitchen'],
      rules: ['No Smoking', 'No Pets', 'Max 2 Guests'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Cozy Cottage Airbnb — Nandi Hills',
      description: 'Escape the city in this charming hillside cottage near Nandi Hills. Fireplace, garden seating and stunning sunrise views.',
      location: 'Nandi Hills, Bangalore', city: 'Bangalore', price: 6500, type: 'Airbnb',
      images: ['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800'],
      amenities: ['Garden', 'Fireplace', 'WiFi', 'Kitchen', 'Parking', 'BBQ Grill'],
      rules: ['No Smoking Inside', 'No Loud Parties', 'Max 4 Guests'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    // Hyderabad Airbnbs
    {
      title: 'Modern Airbnb Studio — Banjara Hills',
      description: 'Sleek self-service studio in posh Banjara Hills. All amenities for a comfortable short stay — smart TV, espresso machine and blackout curtains.',
      location: 'Banjara Hills, Hyderabad', city: 'Hyderabad', price: 3800, type: 'Airbnb',
      images: ['https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800'],
      amenities: ['WiFi', 'Smart TV', 'AC', 'Espresso Machine', 'Self Check-in', 'Workspace'],
      rules: ['No Smoking', 'No Pets', 'Checkout 10am'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Poolside Villa Airbnb — Shamirpet',
      description: 'Exclusive poolside villa on the outskirts of Hyderabad. Great for group getaways, corporate offsites and family reunions.',
      location: 'Shamirpet, Hyderabad', city: 'Hyderabad', price: 18000, type: 'Airbnb',
      images: ['https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800'],
      amenities: ['Private Pool', 'BBQ', 'WiFi', 'AC', 'Full Kitchen', 'Parking x4', 'Garden'],
      rules: ['No Outside Guests', 'Max 10 Guests', 'No Smoking Inside'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    // Delhi Airbnbs
    {
      title: 'Boutique Room Airbnb — Hauz Khas',
      description: 'Elegant private room in a designer apartment in Hauz Khas Village. Steps from the deer park, art galleries and rooftop bars.',
      location: 'Hauz Khas, Delhi', city: 'Delhi', price: 3200, type: 'Airbnb',
      images: ['https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800'],
      amenities: ['WiFi', 'AC', 'Shared Kitchen', 'Netflix', 'Self Check-in'],
      rules: ['No Smoking', 'No Pets', 'Quiet Hours after Midnight'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Heritage Haveli Airbnb — Old Delhi',
      description: 'Stay in a restored 200-year-old Haveli in Chandni Chowk. Stunning rooftop with views of Jama Masjid. Truly unique Delhi experience.',
      location: 'Chandni Chowk, Delhi', city: 'Delhi', price: 8000, type: 'Airbnb',
      images: ['https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800'],
      amenities: ['Rooftop', 'WiFi', 'AC', 'Heritage Architecture', 'Guided Tour Included'],
      rules: ['No Smoking', 'No Alcohol', 'Max 4 Guests'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    // Pune Airbnbs
    {
      title: 'Treehouse Airbnb — Lonavala',
      description: 'Magical treehouse stay near Lonavala, 1hr from Pune. Surrounded by monsoon greenery, with deck hammocks and valley views.',
      location: 'Lonavala, Pune', city: 'Pune', price: 9500, type: 'Airbnb',
      images: ['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800'],
      amenities: ['Deck Hammocks', 'Valley View', 'WiFi', 'Kitchen', 'BBQ', 'Parking'],
      rules: ['No Smoking Inside', 'Max 3 Guests', 'No Loud Music'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Minimalist Studio Airbnb — Koregaon Park',
      description: 'Zen minimalist studio in the heart of Koregaon Park. Perfect for a digital nomad or solo weekend trip to Pune.',
      location: 'Koregaon Park, Pune', city: 'Pune', price: 2800, type: 'Airbnb',
      images: ['https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800'],
      amenities: ['WiFi', 'AC', 'Workspace', 'Netflix', 'Self Check-in', 'Kitchen'],
      rules: ['No Smoking', 'No Pets', 'Max 2 Guests'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    // Chennai Airbnbs
    {
      title: 'Sea View Airbnb — Besant Nagar',
      description: 'Bright and breezy apartment steps from Elliot\'s Beach. Great for couples and solo travellers visiting Chennai.',
      location: 'Besant Nagar, Chennai', city: 'Chennai', price: 4500, type: 'Airbnb',
      images: ['https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800'],
      amenities: ['Beach Access', 'WiFi', 'AC', 'Kitchen', 'Self Check-in', 'Parking'],
      rules: ['No Smoking', 'No Loud Music', 'Max 3 Guests'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Chettinad Style Airbnb — Mylapore',
      description: 'Stay in a restored Chettinad-style bungalow near Kapaleeswarar Temple. Traditional architecture meets modern comforts.',
      location: 'Mylapore, Chennai', city: 'Chennai', price: 6000, type: 'Airbnb',
      images: ['https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800'],
      amenities: ['Heritage Interiors', 'Courtyard', 'WiFi', 'AC', 'Kitchen', 'Parking'],
      rules: ['No Smoking', 'Respectful of Heritage Property', 'Max 4 Guests'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    // Kolkata Airbnbs
    {
      title: 'Victorian Airbnb Apartment — South Kolkata',
      description: 'Charming Victorian-era apartment with high ceilings, wooden floors and vintage furniture in South Kolkata.',
      location: 'Ballygunge, Kolkata', city: 'Kolkata', price: 5000, type: 'Airbnb',
      images: ['https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?w=800'],
      amenities: ['Heritage Decor', 'WiFi', 'AC', 'Kitchen', 'Workspace', 'Parking'],
      rules: ['No Smoking', 'Max 3 Guests', 'No Loud Music'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Modern Studio Airbnb — New Town',
      description: 'Sleek modern studio in Kolkata\'s New Town smart city zone. Close to tech parks and eco park. Ideal for business travellers.',
      location: 'New Town, Kolkata', city: 'Kolkata', price: 2500, type: 'Airbnb',
      images: ['https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800'],
      amenities: ['WiFi', 'AC', 'Workspace', 'Self Check-in', 'Kitchen', 'Smart TV'],
      rules: ['No Smoking', 'No Pets', 'Max 2 Guests'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    // Ahmedabad Airbnbs
    {
      title: 'Heritage Pol-House Airbnb — Old Ahmedabad',
      description: 'Stay in a lovingly restored pol-house in UNESCO Heritage Old Ahmedabad. Intricate wooden carvings and a tranquil inner courtyard.',
      location: 'Old City, Ahmedabad', city: 'Ahmedabad', price: 5500, type: 'Airbnb',
      images: ['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800'],
      amenities: ['Heritage Architecture', 'Courtyard', 'WiFi', 'AC', 'Guided Tour Included'],
      rules: ['No Smoking', 'No Alcohol', 'Max 4 Guests', 'Respect Heritage Property'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
    {
      title: 'Luxury Airbnb Flat — Prahlad Nagar',
      description: 'Fully equipped luxury flat for short stays in Ahmedabad\'s corporate hub. Smart home features, premium appliances and concierge support.',
      location: 'Prahlad Nagar, Ahmedabad', city: 'Ahmedabad', price: 4800, type: 'Airbnb',
      images: ['https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800'],
      amenities: ['Smart Home', 'WiFi', 'AC', 'Kitchen', 'Gym Access', 'Parking', 'Concierge'],
      rules: ['No Smoking', 'No Parties', 'Max 3 Guests'],
      availableFrom: new Date('2026-03-01'), status: 'published', createdBy: admin._id,
    },
  ];

  const properties = await Property.insertMany(propertyData);
  console.log(`${properties.length} properties created`);

  // Create sample visits
  await Visit.insertMany([
    {
      property: properties[0]._id,
      tenant: tenant1._id,
      status: 'scheduled',
      preferredDate: new Date('2026-03-10'),
      scheduledDate: new Date('2026-03-12'),
      notes: 'I want to check the sea view from balcony',
      adminNotes: 'Confirmed for 11 AM',
    },
    {
      property: properties[1]._id,
      tenant: tenant1._id,
      status: 'requested',
      preferredDate: new Date('2026-03-15'),
      notes: 'Looking for something close to office',
    },
    {
      property: properties[2]._id,
      tenant: tenant2._id,
      status: 'visited',
      preferredDate: new Date('2026-03-05'),
      scheduledDate: new Date('2026-03-06'),
    },
    {
      property: properties[4]._id,
      tenant: tenant2._id,
      status: 'decision_pending',
      preferredDate: new Date('2026-03-08'),
      scheduledDate: new Date('2026-03-09'),
    },
  ]);
  console.log('Sample visits created');

  // Create sample support tickets
  await SupportTicket.insertMany([
    {
      property: properties[0]._id,
      raisedBy: tenant1._id,
      subject: 'AC not working in bedroom',
      category: 'maintenance',
      messages: [
        { sender: tenant1._id, senderRole: 'tenant', text: 'The AC in the master bedroom has not been working since yesterday. Please send someone to fix it.', createdAt: new Date() },
      ],
      status: 'open',
    },
    {
      property: properties[2]._id,
      raisedBy: tenant2._id,
      subject: 'Query about move-in date',
      category: 'move-in',
      messages: [
        { sender: tenant2._id, senderRole: 'tenant', text: 'Can we move in a week earlier than the listed date?', createdAt: new Date() },
        { sender: admin._id, senderRole: 'admin', text: 'We will check with the owner and revert within 24 hours.', createdAt: new Date() },
      ],
      status: 'in_progress',
    },
  ]);
  console.log('Sample support tickets created');

  console.log('\n✅ Seed completed!');
  console.log('Demo credentials:');
  console.log('  Admin   — nawazish@gmail.com  / admin@macbook');
  console.log('  Tenant1 — tenant@demo.com / demo123');
  console.log('  Tenant2 — tenant2@demo.com / demo123');

  await mongoose.connection.close();
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed error:', err);
  process.exit(1);
});
